[package]
name = "aoc_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_runner_api = { path = "../aoc_runner_api" }
aoc_solvers = { path = "../aoc_solvers" }
colored = "2.0.4"
itertools = "0.11.0"
nom = "7.1.3"
rayon = "1.7.0"
thiserror = "1.0.47"
