[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
nom = "7.1.1"
num = "0.4.1"
tupletools = "0.3.0"
composing = "0.2.0"
thiserror = "1.0.47"
priority-queue = "1.3.2"
rayon = "1.7.0"
derive_more = "0.99.17"
ahash = "0.8.3"
indexmap = "2.1.0"
